schema_version = "1.0.0"

id = "em_tools"
name = "EM Tools"
version = "{VERSION}"
tagline = "Blender tools for Extended Matrix"
maintainer = "E. Demetrescu <emanuel.demetrescu@cnr.it>"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.4.0"

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
tags = ["3D View", "Import-Export"]

# Permissions required by EM Tools
permissions = { files = "Import and export data", network = "Download resources and updates", clipboard = "Copy and paste data" }

{WHEELS_SECTION}

{DEPENDENCIES_SECTION}