schema_version = "1.0.0"

id = "em_tools"
name = "EM Tools"
version = "1.5.0-dev.52"
tagline = "Blender tools for Extended Matrix"
maintainer = "E. Demetrescu <emanuel.demetrescu@cnr.it>"
type = "add-on"
license = ["GPL-3.0"]

blender_version_min = "4.0.0"

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
tags = ["3D View", "Import-Export", "Tools"]

# Permissions required by EM Tools
permissions = [
    "files",           # File system access for import/export
    "network",         # Network access for updates/remote data
    "clipboard",       # Clipboard access for copy/paste operations
    "camera",          # Camera access for 3D viewport operations
]


# Wheels for dependencies
wheels = [
    "contourpy-1.3.2-cp311-cp311-win_amd64.whl",
    "cycler-0.12.1-py3-none-any.whl",
    "et_xmlfile-2.0.0-py3-none-any.whl",
    "fonttools-4.57.0-cp311-cp311-win_amd64.whl",
    "kiwisolver-1.4.8-cp311-cp311-win_amd64.whl",
    "matplotlib-3.9.3-cp311-cp311-win_amd64.whl",
    "networkx-3.4.2-py3-none-any.whl",
    "numpy-1.26.4-cp311-cp311-win_amd64.whl",
    "openpyxl-3.1.5-py2.py3-none-any.whl",
    "packaging-25.0-py3-none-any.whl",
    "pandas-2.2.3-cp311-cp311-win_amd64.whl",
    "pillow-11.0.0-cp311-cp311-win_amd64.whl",
    "pyparsing-3.2.3-py3-none-any.whl",
    "python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "pytz-2025.1-py2.py3-none-any.whl",
    "pytz-2025.2-py2.py3-none-any.whl",
    "six-1.17.0-py2.py3-none-any.whl",
    "tzdata-2025.1-py2.py3-none-any.whl",
    "tzdata-2025.2-py2.py3-none-any.whl"
]

# Dependencies included via wheels