schema_version = "1.0.0"

id = "em_tools"
name = "EM Tools"
version = "1.5.0-dev.42"
tagline = "Blender tools for Extended Matrix"
maintainer = "E. Demetrescu <emanuel.demetrescu@cnr.it>"
type = "add-on"
license = ["GPL-3.0"]

blender_version_min = "4.0.0"

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
tags = ["3D View", "Import-Export", "Tools"]

[permissions]
wheels = [
    "./wheels/contourpy-1.3.2-cp311-cp311-win_amd64.whl",
    "./wheels/cycler-0.12.1-py3-none-any.whl",
    "./wheels/et_xmlfile-2.0.0-py3-none-any.whl",
    "./wheels/fonttools-4.57.0-cp311-cp311-win_amd64.whl",
    "./wheels/kiwisolver-1.4.8-cp311-cp311-win_amd64.whl",
    "./wheels/matplotlib-3.9.3-cp311-cp311-win_amd64.whl",
    "./wheels/networkx-3.4.2-py3-none-any.whl",
    "./wheels/numpy-1.26.4-cp311-cp311-win_amd64.whl",
    "./wheels/openpyxl-3.1.5-py2.py3-none-any.whl",
    "./wheels/packaging-25.0-py3-none-any.whl",
    "./wheels/pandas-2.2.3-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-11.0.0-cp311-cp311-win_amd64.whl",
    "./wheels/pyparsing-3.2.3-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/pytz-2025.1-py2.py3-none-any.whl",
    "./wheels/pytz-2025.2-py2.py3-none-any.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl",
    "./wheels/tzdata-2025.1-py2.py3-none-any.whl",
    "./wheels/tzdata-2025.2-py2.py3-none-any.whl"
]
